<a href="https://colab.research.google.com/github/VinuthaVM/Domain-tasks/blob/main/classification_metrcs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

In [ ]:
#Reading the dataset
dataset = datasets.load_breast_cancer()
dataset


#dataset = pd.read_csv('')

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
#EDA Steps
X = dataset.data
y = dataset.target

In [ ]:
#Splitting the data into training & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [ ]:
len(X)


569

In [ ]:
len(X_train)

426

In [ ]:
len(X_test)

143

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Why do we have fit_transform for training data & transform for test data

In [ ]:
X_train

array([[ 1.56244985,  0.54326214,  1.55507409, ...,  1.69520465,
         1.85560386, -0.29549769],
       [-0.90339782, -0.99855161, -0.90735793, ..., -0.7382083 ,
         0.47991254, -0.63379366],
       [ 3.71435858,  0.58666134,  3.72524041, ...,  2.36225188,
        -0.0847247 , -0.20757291],
       ...,
       [ 1.53676394, -0.26304935,  1.58833334, ...,  1.68288045,
         1.19958024,  0.40414768],
       [-1.18594287, -0.4046678 , -1.16761159, ..., -0.77749169,
        -0.02271252, -0.43167388],
       [-0.72074244, -0.71531472, -0.70697092, ..., -0.26665367,
        -0.16958348, -0.23866826]])

In [ ]:
#Call the Classifier
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_prob = model.predict_proba(X_test)

In [ ]:
y_pred_prob

array([[0. , 1. ],
       [1. , 0. ],
       [0.2, 0.8],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0.2, 0.8],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.2, 0.8],
       [0. , 1. ],
       [1. ,

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [ ]:
y_test

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [ ]:
#Classification Metrics - To check the final results
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

result1 = accuracy_score(y_test, y_pred)
print('Accuracy is: ', result1*100)

#print(classification_report(y_test, y_pred))
#print(confusion_matrix(y_test, y_pred))

Accuracy is:  98.6013986013986


In [ ]:
#Call the Classifier
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt = model_dt.predict(X_test)

In [ ]:
#Classification Metrics - To check the final results
from sklearn.metrics import accuracy_score

result1 = accuracy_score(y_test, y_pred_dt)
print('Accuracy is: ', result1*100)

Accuracy is:  91.6083916083916


In [ ]:
from sklearn.metrics import log_loss

ll_sk = log_loss(y_test, y_pred_dt)
ll_sk

3.0246422424433974

In [ ]:
ll_sk_knn = log_loss(y_test, y_pred)
ll_sk_knn

0.5041070404072331

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[40  6]
 [ 6 91]]


In [ ]:
from sklearn.metrics import classification_report

cr = classification_report(y_test, y_pred_dt)

print(cr)

              precision    recall  f1-score   support

           0       0.87      0.87      0.87        46
           1       0.94      0.94      0.94        97

    accuracy                           0.92       143
   macro avg       0.90      0.90      0.90       143
weighted avg       0.92      0.92      0.92       143



In [ ]:
from sklearn.metrics import classification_report

cr2 = classification_report(y_test, y_pred)

print(cr2)

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        46
           1       0.98      1.00      0.99        97

    accuracy                           0.99       143
   macro avg       0.99      0.98      0.98       143
weighted avg       0.99      0.99      0.99       143



In [ ]:
from sklearn.metrics import accuracy_score

result1 = accuracy_score(y_test, y_pred_dt)
print('Accuracy is: ', result1*100)

Accuracy is:  91.6083916083916


In [ ]:
from sklearn.metrics import accuracy_score

result2 = accuracy_score(y_test, y_pred)
print('Accuracy is: ', result2*100)

Accuracy is:  98.6013986013986
